"""Type stubs for the Continuum native extension re-exports."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any

class NodeKind: ...
class Node: ...
class Graph: ...
class BackendRegistry:
    def __init__(self) -> None: ...
    def register_default_libtorch(self) -> None: ...
    def register_mlx(self) -> None: ...
    def register_openai(self) -> None: ...
    def register_azure(self) -> None: ...
    def register_fake_llm(self) -> None: ...
    def register_anthropic(self) -> None: ...
    def register_vllm(self) -> None: ...
    def load_plugin(self, name: str, path: str, priority: int = ...) -> None: ...
    def load_plugins_from_env(self, env_var: str = ...) -> int: ...
    def names(self) -> list[str]: ...
    def has(self, name: str) -> bool: ...

def check_backend(
    target: str,
    expect_deterministic: bool = ...,
    prompt: str = ...,
    tensor_op: str = ...,
) -> dict[str, Any]: ...
class GraphBuilder: ...
class Interpreter: ...

class DurableAgent:
    prompt_node_ids: list[int]
    step_node_ids: list[int]
    backend: str

    def __init__(self) -> None: ...
    def begin(
        self,
        prompts: Sequence[str],
        model_id: str | None = ...,
        max_tokens: int = ...,
    ) -> int: ...
    def step_outputs(self) -> list[Any]: ...
    def run_until_step(self, step_index: int) -> bytes: ...
    def resume_from(self, checkpoint: bytes) -> list[Any]: ...
    def cache_size(self) -> int: ...
    @staticmethod
    def inspect(checkpoint: bytes) -> dict[str, Any]: ...
    @staticmethod
    def fork(checkpoint: bytes, node_id: int, new_value: Any) -> bytes: ...

def eager_step(*args: Any, **kwargs: Any) -> Any: ...
def run_tensor_op(*args: Any, **kwargs: Any) -> Any: ...
def train_classifier_demo(*args: Any, **kwargs: Any) -> Any: ...

class Session:
    policy: Any
    cache_namespace: str
    id: str
    run_count: int

    def __init__(
        self,
        id: str,
        backends: BackendRegistry,
        max_cache_entries: int = ...,
    ) -> None: ...
    def run(self, graph: Graph, inputs: Mapping[int, Any]) -> list[Any]: ...
    def metrics(self) -> ReuseMetrics: ...
    def reset_metrics(self) -> None: ...
    def save_cache_metadata(self, path: str) -> bool: ...
    def load_cache_metadata(self, path: str) -> bool: ...
    def cache_size(self) -> int: ...
    def cache_stats(self) -> dict[str, dict[str, int]]: ...
    def generate(
        self,
        prompt_parts: Sequence[str],
        model_id: str,
        max_tokens: int = ...,
        temperature: float = ...,
        op_name: str = ...,
    ) -> Any: ...
    def set_memo_table(self, memo_table: Any) -> None: ...
    def set_semantic_cache(self, sc: Any) -> None: ...
    def set_embedding_provider(self, ep: Any) -> None: ...
    def set_layer_cache(self, lc: Any) -> None: ...
    def set_memory_graph(self, mg: Any) -> None: ...

class ReusePolicyKind: ...
class ReusePolicy: ...
class ReuseMetrics: ...
class ReuseStepRecord: ...
class MemoTable: ...
class MemoKey: ...
class SemanticCacheIndex:
    def __init__(self, max_entries: int = ..., similarity_threshold: float = ...) -> None: ...
    def size(self) -> int: ...
    def max_entries(self) -> int: ...
    def estimated_bytes(self) -> int: ...
    def similarity_threshold(self) -> float: ...
    def set_similarity_threshold(self, t: float) -> None: ...
    def lookup(
        self,
        query_embedding: Sequence[float],
        model_id: str,
        cache_namespace: str = ...,
        embedder_id: str = ...,
    ) -> dict[str, Any]: ...
    def insert(
        self,
        embedding: Sequence[float],
        model_id: str,
        output_bytes: bytes,
        cache_namespace: str = ...,
        embedder_id: str = ...,
    ) -> None: ...
    def clear(self) -> None: ...
    @staticmethod
    def cosine_similarity(a: Sequence[float], b: Sequence[float]) -> float: ...
class MemoryGraphStore: ...
class LayerKVCacheIndex: ...
class FutureCache: ...
class EmbeddingProvider:
    def __init__(self) -> None: ...
    def embed(self, text: str) -> list[float]: ...
    def dimension(self) -> int: ...
    def identity(self) -> str: ...

class BruteForceEmbeddingProvider(EmbeddingProvider):
    def __init__(self, dim: int = ...) -> None: ...

def benchmark_azure_agent(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def benchmark_vllm_agent(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def benchmark_agent_paired(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def benchmark_azure_with_prompt(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def benchmark_azure_isolated(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def benchmark_deterministic_m1(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def run_session_benchmark(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def run_cold_start_benchmark(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def run_v11_benchmark(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def run_v11_wiring_check(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def run_v11_layer_isolation_check(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def validate_v11_features(*args: Any, **kwargs: Any) -> dict[str, Any]: ...

__all__: list[str]
