"""Type stubs for the Continuum native extension re-exports."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any

class NodeKind: ...
class Node: ...
class Graph: ...
class BackendRegistry: ...
class GraphBuilder: ...
class Interpreter: ...

class DurableAgent:
    prompt_node_ids: list[int]
    step_node_ids: list[int]

    def __init__(self) -> None: ...
    def begin(
        self,
        prompts: Sequence[str],
        model_id: str = ...,
        max_tokens: int = ...,
    ) -> int: ...
    def run_until_step(self, step_index: int) -> bytes: ...
    def resume_from(self, checkpoint: bytes) -> list[Any]: ...
    def cache_size(self) -> int: ...
    @staticmethod
    def inspect(checkpoint: bytes) -> dict[str, Any]: ...
    @staticmethod
    def fork(checkpoint: bytes, node_id: int, new_value: Any) -> bytes: ...

def eager_step(*args: Any, **kwargs: Any) -> Any: ...
def run_tensor_op(*args: Any, **kwargs: Any) -> Any: ...
def train_classifier_demo(*args: Any, **kwargs: Any) -> Any: ...

class Session:
    policy: Any
    cache_namespace: str
    id: str
    run_count: int

    def __init__(
        self,
        id: str,
        backends: BackendRegistry,
        max_cache_entries: int = ...,
    ) -> None: ...
    def run(self, graph: Graph, inputs: Mapping[int, Any]) -> list[Any]: ...
    def metrics(self) -> ReuseMetrics: ...
    def reset_metrics(self) -> None: ...
    def save_cache_metadata(self, path: str) -> bool: ...
    def load_cache_metadata(self, path: str) -> bool: ...
    def cache_size(self) -> int: ...
    def set_memo_table(self, memo_table: Any) -> None: ...
    def set_semantic_cache(self, sc: Any) -> None: ...
    def set_embedding_provider(self, ep: Any) -> None: ...
    def set_layer_cache(self, lc: Any) -> None: ...
    def set_memory_graph(self, mg: Any) -> None: ...

class ReusePolicyKind: ...
class ReusePolicy: ...
class ReuseMetrics: ...
class ReuseStepRecord: ...
class MemoTable: ...
class MemoKey: ...
class SemanticCacheIndex: ...
class MemoryGraphStore: ...
class LayerKVCacheIndex: ...
class FutureCache: ...
class EmbeddingProvider: ...
class BruteForceEmbeddingProvider: ...

def benchmark_azure_agent(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def benchmark_vllm_agent(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def benchmark_agent_paired(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def benchmark_azure_with_prompt(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def benchmark_azure_isolated(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def benchmark_deterministic_m1(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def run_session_benchmark(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def run_cold_start_benchmark(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def run_v11_benchmark(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def run_v11_wiring_check(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def run_v11_layer_isolation_check(*args: Any, **kwargs: Any) -> dict[str, Any]: ...
def validate_v11_features(*args: Any, **kwargs: Any) -> dict[str, Any]: ...

__all__: list[str]
